---
profile: updated-bus-dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  rabbitmq:
    username: config-server
    password: config-server
    host: localhost
    port: 5672
