apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: greeting
  name: greeting-svc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: greeting
  type: LoadBalancer
status:
  loadBalancer: {}
